<header><h3>Edit Article Record</h3></header>
	<div class="module_content">
	<div style="float:right">
		<?php
		echo $this->image;
		?>
	</div>
<?php 
echo $this->form;
?>
		<div class="clear"></div>
	</div>
<footer>
	<div class="submit_link">
		<?php  /*
		<select>
			<option>Draft</option>
			<option>Published</option>
		</select>
		<input type="submit" value="Publish" class="alt_btn">
		<input type="submit" value="Reset">
		*/ 
		?>
	</div>
</footer>
