<script type="text/javascript">
	$(".tablesorter").tablesorter(); 


		$(".tab_content").hide(); //Hide all content
		$("ul.tabs li:first").addClass("active").show(); //Activate first tab
		$(".tab_content:first").show(); //Show first tab content
	
		//On Click Event
		$("ul.tabs li").click(function() {
	
			$("ul.tabs li").removeClass("active"); //Remove any "active" class
			$(this).addClass("active"); //Add "active" class to selected tab
			$(".tab_content").hide(); //Hide all tab content
	
			var activeTab = $(this).find("a").attr("href"); 
			//Find the href attribute value to identify the active tab + content
			$(activeTab).fadeIn(); //Fade in the active ID content
			return false;
		});
	

</script>
<article class="module width_full">
<?php 
	
$head =	'
<table class="tablesorter" cellspacing="0"> 
	<thead> 
		<tr> 
    		<th>Report Date</th> 
    		<th>Park</th> 
    		<th>Air Temperature</th> 
    		<th>Water Temperature</th> 
    		<th>Condition</th> 
    		<th></th>
		</tr> 
	</thead> 
	<tbody>';
$foot = '
	</tbody> 
</table>
';

$table = '
<header><h3 class="tabs_involved">Conditions</h3>
</header>
<div class="tab_container">';

#Accom
$table .= '<div id="tab1" class="tab_content">';
$table .= $head;
foreach($this->result as $vals){
	$table .= '
		<tr> 
    		<td>'.$vals['report_date'].'</td> 
    		<td>'.$vals['beach_name'].'</td> 
    		<td>'.$vals['air_temp'].'</td> 
    		<td>'.$vals['water_temp'].'</td> 
    		<td>'.$vals['condition'].'</td> 
    		<td><input type="image" src="images/icn_edit.png" title="Edit" onclick="updateModule({\'u\':\'surf/edit?qid='.$vals['id'].'\'});">
    		</td> 
		</tr>';
}

$table .= $foot;
$table .= '</div>';

$table .= '</div>';
echo $table;
?>
</article>

