<?php 
header('P3P: CP="CAO PSA OUR"');
$username = Zend_Registry::get('username');
$acl = Zend_Registry::get('acl');
?>
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8"/>
	<title>Dashboard I Admin Panel</title>
	
	<link rel="stylesheet" href="css/layout.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="js/jquery-ui-1.10.0.custom/development-bundle/themes/base/jquery.ui.all.css" type="text/css" media="screen" />
	<!--[if lt IE 9]>
	<link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" />
	<script src="js/html5shim.js" type="text/javascript"></script>
	<![endif]-->
	<script src="js/jquery-1.9.1.min.js" type="text/javascript"></script>
	<script src="js/jquery-ui-1.10.0.custom/js/jquery-ui-1.10.0.custom.min.js" type="text/javascript"></script>
	<?php /* 	?>
	<script src="js/jquery-ui-1.10.0.custom/development-bundle/ui.widget.js" type="text/javascript"></script>
	<script src="js/jquery-ui-1.10.0.custom/development-bundle/ui.datepicker.js" type="text/javascript"></script>
	<?php */ 	?>
	<script src="js/jquery.form.js" type="text/javascript"></script>
	<script src="js/hideshow.js" type="text/javascript"></script>
	<script src="js/jquery.tablesorter.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/jquery.equalHeight.js"></script>
	<script type="text/javascript">
	$(document).ready(function() 
    	{ 
      	  $(".tablesorter").tablesorter(); 
   	 } 
	);
	$(document).ready(function() 
		{ 
			<?php #Comment to keep messages ?>
			window.setInterval(timedMessage, 3000);
			function timedMessage() { $("#timed-message").hide('slow'); }
		}
	);
	$(document).ready(function() {
		//When page loads...
		$(".tab_content").hide(); //Hide all content
		$("ul.tabs li:first").addClass("active").show(); //Activate first tab
		$(".tab_content:first").show(); //Show first tab content
	
		//On Click Event
		$("ul.tabs li").click(function() {
	
			$("ul.tabs li").removeClass("active"); //Remove any "active" class
			$(this).addClass("active"); //Add "active" class to selected tab
			$(".tab_content").hide(); //Hide all tab content
	
			var activeTab = $(this).find("a").attr("href"); 
			//Find the href attribute value to identify the active tab + content
			$(activeTab).fadeIn(); //Fade in the active ID content
			return false;
		});
	
	});
    </script>
    <script type="text/javascript">
    $(function(){
        $('.column').equalHeight();
    });
    </script>
    <script type="text/javascript">
    function updateModule(opts){
    	/*m,u,t='#timed-message',e=true*/
    	var default_args = {
    			'm'	:	'#mainform',
    			'u'	:	'',
    			't'	:	'#timed-message',
    			'e':	true
    		}
    		for(var index in default_args) {
    			if(typeof opts[index] == "undefined") opts[index] = default_args[index];
    		}
    	$(opts['m']).load(opts['u'],function(){
        	<?php 
    		//$('form').submit(function() {
    		//http://jquery.malsup.com/form/
    		?>
    			var options = { 
    			        target:        opts['t'],   // target element(s) to be updated with server response 
    			        beforeSubmit:  showRequest,  // pre-submit callback 
    			        success:       (opts['e'])?showResponse:''  // post-submit callback 
    			        <?php 
    			        // other available options: 
    			        //url:       url         // override for form's 'action' attribute 
    			        //type:      type        // 'get' or 'post', override for form's 'method' attribute 
    			        //dataType:  null        // 'xml', 'script', or 'json' (expected server response type) 
    			        //clearForm: true        // clear all form fields after successful submit 
    			        //resetForm: true        // reset the form after successful submit 
    			 
    			        // $.ajax options can be used here too, for example: 
    			        //timeout:   3000 
    			        ?>    			  
    			    }; 
    			 
    			    // bind form using 'ajaxForm' 
    			    $(opts['m']+' form').ajaxForm(options); 
    			    <?php 
        		//alert( $('form').serialize());
        		/*
    			$.post($('form').attr('action'), $('form').serialize(), function(data) {
    		        $("#timed-message").html(data);
    		        $("#timed-message").show();
				});
    		    return false;
    		    */
			//});
			?>
		});
		$('.current').html(opts['u']);
		$(opts['m']).show();
    	//$(opts['m']).load(opts['u']);
    }
    // pre-submit callback 
    function showRequest(formData, jqForm, options) { 
        // formData is an array; here we use $.param to convert it to a string to display it 
        // but the form plugin does this for you automatically when it submits the data 
        var queryString = $.param(formData); 
        <?php      
        // jqForm is a jQuery object encapsulating the form element.  To access the 
        // DOM element for the form do this: 
        // var formElement = jqForm[0]; 
        /*    
        alert('About to submit: \n\n' + queryString); 
        */     
        // here we could return false to prevent the form from being submitted; 
        // returning anything other than false will allow the form submit to continue 
        ?>
        return true; 
    } 
     
    // post-submit callback 
    function showResponse(responseText, statusText, xhr, $form)  { 
        <?php 
        // for normal html responses, the first argument to the success callback 
        // is the XMLHttpRequest object's responseText property 
     
        // if the ajaxForm method was passed an Options Object with the dataType 
        // property set to 'xml' then the first argument to the success callback 
        // is the XMLHttpRequest object's responseXML property 
     
        // if the ajaxForm method was passed an Options Object with the dataType 
        // property set to 'json' then the first argument to the success callback 
        // is the json data object returned by the server 
        /*     
        alert('status: ' + statusText + '\n\nresponseText: \n' + responseText + 
            '\n\nThe output div should have already been updated with the responseText.'); 
        */
        ?>
        //$("#timed-message").html(data);
        $("#timed-message").show();
        $('input[type="submit"]').attr('disabled','disabled');
    } 
</script>

</head>


<body class="tundra">

	<header id="header">
		<hgroup>
			<h1 class="site_title"><a href="../tourism">Tourism PEI</a></h1>
			<h2 class="section_title">Web Admin <?php echo ($_ENV['APPLICATION_ENV']=='production'?"":": Development")?></h2>
			<?php  /* 
			<div class="btn_view_site"><a href="http://www.medialoot.com">View Site</a></div> 
			*/ ?>
		</hgroup>
	</header> <!-- end of header bar -->
	
	<section id="secondary_bar">
		<div class="user">
			<p> <?php echo (isset($username)?$username:'');/* (<a href="#">3 Messages</a>) */ ?></p>
			<!-- <a class="logout_user" href="#" title="Logout">Logout</a> -->
		</div>
		<div class="breadcrumbs_container">
			<article class="breadcrumbs">
			<a href="../tourism">TPEI Web Apps</a> <div class="breadcrumb_divider"></div> 
			<a class="current">Dashboard</a></article>
		</div>
	</section><!-- end of secondary bar -->
	
	<aside id="sidebar" class="column" style="height:100%" >
	<?php  /*
		<form class="quick_search">
			<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};
			this._haschanged=true;">
		</form>
		<hr/>
		*/ ?>
		<?php /*
		<h3>Content</h3>
		<ul class="toggle">
			<li class="icn_new_article"><a href="#">New Article</a></li>
			<li class="icn_edit_article"><a href="#">Edit Articles</a></li>
			<li class="icn_categories"><a href="#">Categories</a></li>
			<li class="icn_tags"><a href="#">Tags</a></li>
		</ul>
		<h3>Users</h3>
		<ul class="toggle">
			<li class="icn_add_user"><a href="#">Add New User</a></li>
			<li class="icn_view_users"><a href="#">View Users</a></li>
			<li class="icn_profile"><a href="#">Your Profile</a></li>
		</ul>
		<h3>Media</h3>
		<ul class="toggle">
			<li class="icn_folder"><a href="#">File Manager</a></li>
			<li class="icn_photo"><a href="#">Gallery</a></li>
			<li class="icn_audio"><a href="#">Audio</a></li>
			<li class="icn_video"><a href="#">Video</a></li>
		</ul>
		<h3>Admin</h3>
		<ul class="toggle">
			<li class="icn_settings"><a href="#">Options</a></li>
			<li class="icn_security"><a href="#">Security</a></li>
			<li class="icn_jump_back"><a href="#">Logout</a></li>
		</ul>
		*/ 
		if($acl->isAllowed($username, 'Coupons')){
		?>
		<h3>Coupons</h3>
		<ul class="toggle">
			<li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'coupons/add'});">New Coupon</a></li>
			<li class="icn_categories"><a href="javascript://" onclick="updateModule({'u':'coupons/list'});">List Coupons</a></li>
			<li class="icn_edit_article"><a href="javascript://" onclick="updateModule({'u':'coupons/tag'});">Add Tag</a></li>
			<?php 
			if($acl->isAllowed($username, 'Advanced Tags')){
			?>
			<li class="icn_edit_article"><a href="javascript://" onclick="updateModule({'u':'coupons/hiddentag'});">Advanced Tag</a></li>
			<?php 
			}
			?>
		</ul>
		<?php 
		}
		if($acl->isAllowed($username, 'Media Stories')){
		?>

		<h3>News Media</h3>
		<ul class="toggle">
			<li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'news-media/add'});">New Article</a></li>
			<li class="icn_categories"><a href="javascript://" onclick="updateModule({'u':'news-media/listall'});">List Articles</a></li>
		</ul>
		<?php 
		}
		if($acl->isAllowed($username, 'User Permissions')){
		?>

		<h3>User Information</h3>
		<ul class="toggle">
			<li class="icn_add_user"><a href="javascript://" onclick="updateModule({'u':'users/add'});">Add User</a></li>
			<li class="icn_view_users"><a href="javascript://" onclick="updateModule({'u':'users'});">List Users</a></li>
		</ul>
		<?php 
		}
		?>
		<?php 
		if($acl->isAllowed($username, 'Snow')){
		?>

		<h3>Snow Conditions</h3>
		<ul class="toggle">
			<li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'snow'});">General</a></li>
			<li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'snow/alpine'});">Alpine</a></li>
			<li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'snow/nordic'});">Nordic</a></li>
                        <li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'snow/nordictrails'});">Nordic Trails</a></li>
		</ul>
		<?php 
		}
		?>
		<?php 
		if($acl->isAllowed($username, 'QTS')){
		?>

		<h3>QTS</h3>
		<ul class="toggle">
			<li class="icn_edit_article"><a href="javascript://" onclick="updateModule({'u':'qts/add'});">Add</a></li>
			<li class="icn_folder"><a href="javascript://" onclick="updateModule({'m':'#subform','u':'qts/find','t':'#mainform','e':false});">Find</a>
			<span style="display:block;float:right;font:10px 'Helvetica Neue',Helvetica,Arial,Verdana,sans-serif;text-shadow: 0 1px 0 #FFFFFF;text-transform: uppercase;color: #666666;margin:4px 16px;cursor:pointer" onclick="" class="toggleSub">Hide</span>
			</li>
			<li class="icn_categories"><a href="javascript://" onclick="updateModule({'u':'qts/listall'});">List All</a></li>
			
		</ul>
		<?php 
		}
		?>
		<?php 
		if($acl->isAllowed($username, 'Surf')){
		?>

		<h3>Surf Conditions</h3>
		<ul class="toggle">
			<!-- <li class="icn_new_article"><a href="javascript://" onclick="updateModule({'u':'surf'});">Create Record</a></li> -->
			<li class="icn_folder"><a href="javascript://" onclick="updateModule({'u':'surf/list'});">View Records</a></li>
		</ul>
		<?php 
		}
		?>
		<footer>
		<?php /*
			<hr />
			<p><strong>Copyright &copy; 2011 Website Admin</strong></p>
			<p>Theme by <a href="http://www.medialoot.com">MediaLoot</a></p>
		*/ ?>
		</footer>
	</aside><!-- end of sidebar -->
	
	<section id="main" class="column">
		<div id="timed-message">
		<h4 class="alert_info">Welcome to the Tourism PEI Web Applications Admin.</h4>
		</div>
		<?php /*
		<article class="module width_full">
			<header><h3>Stats</h3></header>
			<div class="module_content">
				<article class="stats_graph">
					<img src="http://chart.apis.google.com/chart?chxr=0,0,3000&chxt=y&chs=520x140&cht=lc&chco=76A4FB,80C65A&chd=s:Tdjpsvyvttmiihgmnrst,OTbdcfhhggcTUTTUadfk&chls=2|2&chma=40,20,20,30" width="520" height="140" alt="" />
				</article>
				
				<article class="stats_overview">
					<div class="overview_today">
						<p class="overview_day">Today</p>
						<p class="overview_count">1,876</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,103</p>
						<p class="overview_type">Views</p>
					</div>
					<div class="overview_previous">
						<p class="overview_day">Yesterday</p>
						<p class="overview_count">1,646</p>
						<p class="overview_type">Hits</p>
						<p class="overview_count">2,054</p>
						<p class="overview_type">Views</p>
					</div>
				</article>
				<div class="clear"></div>
			</div>
		</article><!-- end of stats article -->
		*/ ?>
		<?php  /*
		<article class="module width_3_quarter">
		
		
		</article><!-- end of content manager article -->
		*/ ?>
		<?php  /*
		<article class="module width_quarter">
			<header><h3>Messages</h3></header>
			<div class="message_list">
				<div class="module_content">
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
				</div>
			</div>
			<footer>
				<form class="post_message">
					<input type="text" value="Message" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
					<input type="submit" class="btn_post_message" value=""/>
				</form>
			</footer>
		</article><!-- end of messages article -->
		*/ ?>
		<div class="clear"></div>
		<div id="subform"></div>
		<div class="clear"></div>
		<div id="mainform"></div>
		<?php 
		#<progress></progress>
		echo $this->layout()->content;
		?>
		</article><!-- end of post new article -->
		
		<?php  /*
		<h4 class="alert_warning">A Warning Alert</h4>
		
		<h4 class="alert_error">An Error Message</h4>
		
		<h4 class="alert_success">A Success Message</h4>
		
		<article class="module width_full">
			<header><h3>Basic Styles</h3></header>
				<div class="module_content">
					<h1>Header 1</h1>
					<h2>Header 2</h2>
					<h3>Header 3</h3>
					<h4>Header 4</h4>
					<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mattis consectetur purus sit amet fermentum. Maecenas faucibus mollis interdum. Maecenas faucibus mollis interdum. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>

<p>Donec id elit non mi porta <a href="#">link text</a> gravida at eget metus. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.</p>

					<ul>
						<li>Donec ullamcorper nulla non metus auctor fringilla. </li>
						<li>Cras mattis consectetur purus sit amet fermentum.</li>
						<li>Donec ullamcorper nulla non metus auctor fringilla. </li>
						<li>Cras mattis consectetur purus sit amet fermentum.</li>
					</ul>
				</div>
		</article><!-- end of styles article -->
		*/ ?>
		
		<div class="spacer"></div>
	</section>


</body>

</html>