<article class="module width_full">
<header><h3>Edit Operator</h3></header>
	<div class="module_content">
		<div style="float:right;width:400px">
		<h4>PDF Files Uploaded</h4>
		<?php 
		//Zend_Debug::dump($this->listlinks);
		echo $this->links($this->listlinks,true);
		?>
		</div>	
		<?php 
		echo $this->form;
		?>			
		<div class="clear"></div>
	</div>	
<footer>
	<div class="submit_link">	
	</div>
</footer>
</article>
